---
title: "PSTAT 174 Final Project Code"
author: "Evan Hu"
date: "2022-11-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, messages = FALSE, warning = FALSE, results = FALSE)
```

```{r,echo=TRUE,eval=FALSE}
#load packages
library(MASS)
library(tidyverse)
library(qpcR)

# load data 
cpi_transport_list <- read.csv("/Users/evanhu/Desktop/PSTAT 174/final project/ccpi_transportation_us.csv")
cpi_transport_list <- select(cpi_transport_list, "Value")
cpi_transport_double <- unlist(cpi_transport_list) # convert from 'list' to 'double' object
cpi_transport <- ts(cpi_transport_double, start = c(1990, 1), end=c(2007,12), frequency = 12) # create time series object
```
* Plot of the original series
```{r,echo=TRUE,eval=FALSE}
par(mfrow=c(2, 1))
ts.plot(cpi_transport, main = "Monthly C-CPI of Public Transportation (January 1990 - December 2007)", ylab = "C-CPI")

ts.plot(cpi_transport_double, main = "Monthly C-CPI of Public Transportation (January 1990 - December 2007)", ylab =  "C-CPI")
fit <- lm(cpi_transport_double ~ as.numeric(1:length(cpi_transport_double)))
abline(fit, col="red") # add trend to data plot 
abline(h=mean(cpi_transport_double), col="blue") # add mean to data plot 

x <- ts(as.ts(cpi_transport), frequency = 12)
decomp <- decompose(x)
plot(decomp)
```
* Training/testing split, work with training set
```{r,echo=TRUE,eval=FALSE}
train_data <- cpi_transport[c(1:200)] # training set 
test_data <- cpi_transport[c(201:216)] # testing set 

# plot training data 
plot.ts(train_data)
fit <- lm(train_data ~ as.numeric(1:length(train_data)))
abline(fit, col="red")
abline(h=mean(train_data), col="blue")
```
* Differencing data
```{r,echo=TRUE,eval=FALSE}
var(train_data)
mean(train_data)

d12_cpi <- diff(train_data, lag = 12, 1)
var(d12_cpi)
mean(d12_cpi)

stat_cpi <- diff(d12_cpi, lag = 1, 1)
var(stat_cpi)
mean(stat_cpi)
par(mfrow=c(2, 1))
# plot of seasonally differenced data 
ts.plot(d12_cpi, main = "Differenced to remove seasonality") 
fit <- lm(d12_cpi ~ as.numeric(1:length(d12_cpi)))
abline(fit, col="red")
abline(h=mean(d12_cpi), col="blue")

# plot of stationary data 
ts.plot(stat_cpi, main = "Differenced to remove seasonality and trend") 
fit <- lm(stat_cpi ~ as.numeric(1:length(stat_cpi)))
abline(fit, col="red")
abline(h=mean(stat_cpi), col="blue")
par(mfrow=c(1, 2))
# Histograms of original and differenced data
hist(train_data, density = 20, breaks = 20, col= "blue", xlab="", main="Histogram of Training Data", prob = TRUE)
m<-mean(train_data)
std<- sqrt(var(train_data))
curve(dnorm(x,m,std), add=TRUE )

hist(stat_cpi, density=20,breaks=20, col="blue", xlab="", prob=TRUE)
m<-mean(stat_cpi)
std<- sqrt(var(stat_cpi))
curve(dnorm(x,m,std), add=TRUE )
```
* Sample ACF/PACF
```{r,echo=TRUE,eval=FALSE}
par(mfrow=c(2, 1))
acf(train_data, lag.max = 80, main = "")
pacf(train_data, lag.max = 80, main = "")

acf(stat_cpi, lag.max = 200, main = "ACF")
pacf(stat_cpi, lag.max = 200, main = "PACF")

acf(stat_cpi, lag.max = 40, main = "ACF")
pacf(stat_cpi, lag.max = 40, main = "PACF")
```

```{r,echo=TRUE,eval=FALSE}
fit1 <- arima(train_data, order = c(2, 1, 2), seasonal = list(order = c(0,1,1), period = 12), method = "ML")
fit2 <- arima(train_data, order = c(2, 1, 2), seasonal = list(order = c(0,1,1), period = 12), method = "ML", fixed =c(0,NA,0,NA,NA))
fit3 <- arima(train_data, order = c(3, 1, 2), seasonal = list(order = c(0,1,1), period = 12), method = "ML",fixed =c(0,NA,NA,0,NA,NA))
fit4 <- arima(train_data, order = c(3, 1, 2), seasonal = list(order = c(0,1,1), period = 12), method = "ML", fixed = c(0,0,NA,0,NA,NA))
fit5 <- arima(train_data, order = c(3, 1, 3), seasonal = list(order = c(0,1,1), period = 12), method = "ML",fixed =c(0,NA,NA,0,NA,NA,NA))
AICc(fit1)
AICc(fit2)
AICc(fit3)
AICc(fit4)
AICc(fit5)
```

```{r,echo=TRUE,eval=FALSE}
fit6 <- arima(train_data, order = c(3, 1, 8), seasonal = list(order = c(0,1,1), period = 12), method = "ML",fixed =c(0,0,NA,0,NA,0,0,0,0,0,NA,NA))
fit6
fit7 <-arima(train_data, order = c(3, 1, 10), seasonal = list(order = c(0,1,1), period = 12), method = "ML",fixed =c(0,0,NA,0,NA,0,0,0,0,0,0,0,NA,NA))
fit7
fit8 <-arima(train_data, order = c(3, 1, 10), seasonal = list(order = c(0,1,1), period = 12), method = "ML",fixed =c(0,0,NA,0,NA,0,0,0,0,0,NA,0,NA,NA))
fit8
fit9 <- arima(train_data, order = c(4, 1, 2), seasonal = list(order = c(0,1,1), period = 12), method = "ML", fixed = c(0,0,NA,NA,0,NA,NA))
fit9
fit10 <- arima(train_data, order = c(4, 1, 3), seasonal = list(order = c(0,1,1), period = 12), method = "ML", fixed = c(0,0,NA,NA,0,NA,NA,NA))
fit10 
fit11 <- arima(train_data, order = c(3, 1, 3), seasonal = list(order = c(0,1,1), period = 12), method = "ML", fixed = c(0,0,NA,0,NA,NA,NA))
fit11 
AICc(fit9)
AICc(fit10)
AICc(fit11)
```

```{r,echo=TRUE,eval=FALSE}
# model to consider
model1 <- arima(train_data, order = c(3, 1, 2), seasonal = list(order = c(0,1,1), period = 12), method = "ML",fixed =c(0,0,NA,0,NA,NA))
res1 <- residuals(model1)

par(mfrow=c(2, 2))
# diagnostic check for model 1 
hist(res1, density=20, breaks=20, col="blue", xlab="", prob=TRUE)
m <- mean(res1)
std <- sqrt(var(res1))
curve(dnorm(x,m,std), add=TRUE )

plot.ts(res1, main = "Plot of residuals")
res_fit1 <- lm(res1 ~ as.numeric(1:length(res1)))
abline(res_fit1, col="red")
abline(h=mean(res1), col="blue")

qqnorm(res1,main= "Normal Q-Q Plot for Chosen Model")
qqline(res1,col="blue")

par(mfrow=c(2, 1))
acf(res1, lag.max=80)
pacf(res1, lag.max=80)

par(mfrow=c(1, 1))
shapiro.test(res1)
Box.test(res1, lag = 20, type = c("Box-Pierce"), fitdf = 3) 
Box.test(res1, lag = 20, type = c("Ljung-Box"), fitdf = 3)
Box.test(res1^2, lag = 20, type = c("Ljung-Box"), fitdf = 0)
acf(res1^2, lag.max=40)
ar(res1, aic = TRUE, order.max = NULL, method = c("yule-walker"))

```

```{r,echo=TRUE,eval=FALSE}
model2 <- arima(train_data, order = c(3, 1, 3), seasonal = list(order = c(0,1,1), period = 12), method = "ML",fixed =c(0,NA,NA,0,NA,NA,NA))

res2 <- residuals(model2)

par(mfrow=c(2, 2))
# diagnostic check for model 2 
hist(res2, density=20, breaks=20, col="blue", xlab="", prob=TRUE)
m <- mean(res2)
std <- sqrt(var(res2))
curve(dnorm(x,m,std), add=TRUE)

plot.ts(res2, main = "Plot of residuals")
res_fit2 <- lm(res2 ~ as.numeric(1:length(res2)))
abline(res_fit2, col="red")
abline(h=mean(res2), col="blue")

qqnorm(res2,main= "Normal Q-Q Plot for Chosen Model")
qqline(res2,col="blue")

par(mfrow=c(2, 1))
acf(res2, lag.max=80)
pacf(res2, lag.max=80)

par(mfrow=c(1, 1))
shapiro.test(res2)
Box.test(res2, lag = 20, type = c("Box-Pierce"), fitdf = 5) 
Box.test(res2, lag = 20, type = c("Ljung-Box"), fitdf = 5)
Box.test(res2^2, lag = 20, type = c("Ljung-Box"), fitdf = 0)
acf(res2^2, lag.max=40)
ar(res2, aic = TRUE, order.max = NULL, method = c("yule-walker"))
```

```{r,echo=TRUE,eval=FALSE}
model3 <- arima(train_data, order = c(3, 1, 4), seasonal = list(order = c(0,1,1), period = 12), method = "ML",fixed =c(0,NA,NA,0,NA,0,NA,NA))

res3 <- residuals(model3)

par(mfrow=c(2, 2))
# diagnostic check for model 2 
hist(res3, density=20, breaks=20, col="blue", xlab="", prob=TRUE)
m <- mean(res3)
std <- sqrt(var(res3))
curve(dnorm(x,m,std), add=TRUE)

plot.ts(res3, main = "Plot of residuals")
res_fit3 <- lm(res3 ~ as.numeric(1:length(res3)))
abline(res_fit3, col="red")
abline(h=mean(res3), col="blue")

qqnorm(res3,main= "Normal Q-Q Plot for Chosen Model")
qqline(res3,col="blue")

par(mfrow=c(2, 1))
acf(res3, lag.max=80)
pacf(res3, lag.max=80)

par(mfrow=c(1, 1))
shapiro.test(res3)
Box.test(res3, lag = 20, type = c("Box-Pierce"), fitdf = 5) 
Box.test(res3, lag = 20, type = c("Ljung-Box"), fitdf = 5)
Box.test(res3^2, lag = 20, type = c("Ljung-Box"), fitdf = 0)
acf(res3^2, lag.max=40)
ar(res3, aic = TRUE, order.max = NULL, method = c("yule-walker"))
```
* Check invertibility and stationarity of model 
```{r,echo=TRUE,eval=FALSE}
plot.roots <- function(ar.roots=NULL, ma.roots=NULL, size=2, angles=FALSE, special=NULL, sqecial=NULL,my.pch=1,first.col="blue",second.col="red",main=NULL)
{xylims <- c(-size,size)
      omegas <- seq(0,2*pi,pi/500)
      temp <- exp(complex(real=rep(0,length(omegas)),imag=omegas))
      plot(Re(temp),Im(temp),typ="l",xlab="x",ylab="y",xlim=xylims,ylim=xylims,main=main)
      abline(v=0,lty="dotted")
abline(h=0,lty="dotted") 
if(!is.null(ar.roots))
        {
          points(Re(1/ar.roots),Im(1/ar.roots),col=first.col,pch=my.pch)
          points(Re(ar.roots),Im(ar.roots),col=second.col,pch=my.pch)}
if(!is.null(ma.roots))
        {
          points(Re(1/ma.roots),Im(1/ma.roots),pch="*",cex=1.5,col=first.col)
          points(Re(ma.roots),Im(ma.roots),pch="*",cex=1.5,col=second.col)}
if(angles)
{
if(!is.null(ar.roots))
            {
              abline(a=0,b=Im(ar.roots[1])/Re(ar.roots[1]),lty="dotted")
              abline(a=0,b=Im(ar.roots[2])/Re(ar.roots[2]),lty="dotted")}
  if(!is.null(ma.roots))
{
sapply(1:length(ma.roots), function(j) abline(a=0,b=Im(ma.roots[j])/Re(
ma.roots[j]),lty="dotted"))
            }}
if(!is.null(special))
        {lines(Re(special),Im(special),lwd=2)}
if(!is.null(sqecial))
        {lines(Re(sqecial),Im(sqecial),lwd=2)
} }
par(mfrow=c(1,2))
plot.roots(NULL,polyroot(c(1, 0, 0.6, 0, -0.28, 0.13)), main="Roots of MA part, nonseasonal ")
plot.roots(NULL,polyroot(c(1, 0, 0.8903, -0.1293)), main="Roots of AR part, nonseasonal ")
```

* Diagnostic checking for final model
```{r,echo=TRUE,eval=FALSE}
final_model <-arima(train_data, order = c(3, 1, 5), seasonal = list(order = c(0,1,1), period = 12), method = "ML",fixed =c(0,NA,NA,0,NA,0,NA,NA,NA))

final_model

par(mfrow=c(2, 2))

res <- residuals(final_model)
hist(res, density=20, breaks=20, col="blue", xlab="", prob=TRUE)
m <- mean(res)
std <- sqrt(var(res))
curve( dnorm(x,m,std), add=TRUE )


plot.ts(res, main = "Plot of residuals")
res_fit <- lm(res ~ as.numeric(1:length(res)))
abline(res_fit, col="red")
abline(h=mean(res), col="blue")

qqnorm(res,main= "Normal Q-Q Plot for Chosen Model")
qqline(res,col="blue")

par(mfrow=c(2, 1))
acf(res, lag.max=80)
pacf(res, lag.max=80)

par(mfrow=c(1, 1))
shapiro.test(res)
Box.test(res, lag = 20, type = c("Box-Pierce"), fitdf = 6) 
Box.test(res, lag = 20, type = c("Ljung-Box"), fitdf = 6)
Box.test(res^2, lag = 20, type = c("Ljung-Box"), fitdf = 0)
acf(res^2, lag.max=40)
ar(res, aic = TRUE, order.max = NULL, method = c("yule-walker"))
```

* Forecasting 
```{r,echo=TRUE,eval=FALSE}
library(forecast)
forecast(final_model)
```
* Plots for forecasting
```{r,echo=TRUE,eval=FALSE}
pred.law <- predict(final_model, n.ahead = 16)
pred.law$pred
U.law= pred.law$pred + 2*pred.law$se #upper bound of prediction interval 
L.law= pred.law$pred - 2*pred.law$se #lower bound
ts.plot(train_data, xlim=c(1,length(train_data)+16), ylim = c(min(train_data),max(U.law)))
lines(U.law, col="blue", lty="dashed")
lines(L.law, col="blue", lty="dashed")
points((length(train_data)+1):(length(train_data)+16), pred.law$pred, col="red")
```

```{r,echo=TRUE,eval=FALSE}
par(mfrow=c(2,1))
ts.plot(train_data, xlim = c(150,length(train_data)+16), ylim = c(min(L.law),max(U.law)))
lines(U.law, col="blue", lty="dashed")
lines(L.law, col="blue", lty="dashed")
points((length(train_data)+1):(length(train_data)+16), pred.law$pred, col="red")

ts.plot(cpi_transport_double, xlim = c(175,length(train_data)+16), ylim = c(220,max(U.law)))
lines(U.law, col="blue", lty="dashed")
lines(L.law, col="blue", lty="dashed")
points((length(train_data)+1):(length(train_data)+16), pred.law$pred, col="red")
```








